### ISSUE TITLE
Possible mistake on your blog post

### ISSUE THREAD

**Issue by quentin-dev** [Grieverheart/space_invaders#1]
In your 1st blog post, you write that the command to compile the code is 

> g++ -std=c++11 -o main -lglfw -lglew -framework OpenGL main.cpp

But, for me, on the latest Fedora release, it was the command you suggested for Mac OS X that worked

> g++ -std=c++11 -o main -lglfw -lGLEW -lGL main.cpp

Is this a mistake on your end, or just Fedora being weird ? (Very cool tutorials by the way)

**Comment by Grieverheart** [comment]
Hi Quentin,

Thank you very much for letting me know. It is indeed a mistake, the osx
and linux commands should be swapped.

Cheers,

Nick
