### ISSUE TITLE
error after compiling on linux

### ISSUE THREAD

**Issue by geofflangenderfer** [Grieverheart/space_invaders#7]
This works fine:

    g++ -std=c++11 -o main -lglfw -lGLEW -lGL main.cpp

but running the following throws an error:

    geoff@ubuntu:~/work/interview$ ./main 
    libGL error: unable to load driver: radeonsi_dri.so
    libGL error: driver pointer missing
    libGL error: failed to load driver: radeonsi
    libGL error: unable to load driver: radeonsi_dri.so
    libGL error: driver pointer missing
    libGL error: failed to load driver: radeonsi
    libGL error: unable to load driver: swrast_dri.so
    libGL error: failed to load driver: swrast
    Error: GLX: Failed to create context: GLXBadFBConfig

**Comment by Grieverheart** [comment]
Hi geofflangenderfer. This seems like a driver issue I cannot solve. Are you perhaps using Ubuntu 16.04? If yes, if you google the errors you will see that there is a known problem in that release.
